-- Expand ADMIN_IMPORT / ADMIN_EXPORT permissions (code) and rename
-- EXPORT_BULKING_DOCUMENTATION -> EXPORT_BULKING_DOCUMENT.

UPDATE users
SET role = 'EXPORT_BULKING_DOCUMENT'
WHERE UPPER(TRIM(role)) = 'EXPORT_BULKING_DOCUMENTATION';

ALTER TABLE users
  DROP CONSTRAINT IF EXISTS chk_users_role;

ALTER TABLE users
  ADD CONSTRAINT chk_users_role
  CHECK (
    UPPER(TRIM(role)) IN (
      'ADMIN',
      'ADMIN_IMPORT',
      'ADMIN_EXPORT',
      'IMPORT_OFFICER',
      'VIEWER',
      'DOCS',
      'EXPORT_BULKING_OPERATION',
      'EXPORT_BULKING_LEAD_DOCUMENTATION',
      'EXPORT_BULKING_DOCUMENT'
    )
  );
