/**
 * RBAC: roles, permissions, and role→permission mapping (API Spec §7 Access Control Matrix).
 * Business rules live here; middleware only calls hasPermission.
 */

/** Supported roles (align with API Spec). */
export const ROLES = {
  ADMIN: "ADMIN",
  ADMIN_IMPORT: "ADMIN_IMPORT",
  ADMIN_EXPORT: "ADMIN_EXPORT",
  IMPORT_OFFICER: "IMPORT_OFFICER",
  /** Legacy name; still present in some production DBs (same privileges as IMPORT_OFFICER). */
  EXIM_OFFICER: "EXIM_OFFICER",
  VIEWER: "VIEWER",
  DOCS: "DOCS",
  EXPORT_BULKING_OPERATION: "EXPORT_BULKING_OPERATION",
  EXPORT_BULKING_LEAD_DOCUMENTATION: "EXPORT_BULKING_LEAD_DOCUMENTATION",
  EXPORT_BULKING_DOCUMENT: "EXPORT_BULKING_DOCUMENT",
  /** Legacy name; still present in some DBs until migration 101 (same privileges as EXPORT_BULKING_DOCUMENT). */
  EXPORT_BULKING_DOCUMENTATION: "EXPORT_BULKING_DOCUMENTATION",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

/** Active users with either role receive import shipment ETA H-3/H-2/H-1 notifications. */
export const IMPORT_ETA_REMINDER_ROLES: readonly string[] = [
  ROLES.IMPORT_OFFICER,
  ROLES.EXIM_OFFICER,
];

/** Permissions from Access Control Matrix. */
export const PERMISSIONS = {
  VIEW_TRANSACTIONS: "VIEW_TRANSACTIONS",
  CREATE_TRANSACTION: "CREATE_TRANSACTION",
  UPDATE_TRANSACTION: "UPDATE_TRANSACTION",
  UPDATE_STATUS: "UPDATE_STATUS",
  UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT",
  MANAGE_USERS: "MANAGE_USERS",
  VIEW_PO_INTAKE: "VIEW_PO_INTAKE",
  UPDATE_PO_INTAKE: "UPDATE_PO_INTAKE",
  TAKE_OWNERSHIP: "TAKE_OWNERSHIP",
  CREATE_PO_INTAKE_TEST: "CREATE_PO_INTAKE_TEST",
  IMPORT_PO_CSV: "IMPORT_PO_CSV",
  PARSE_PO_PDF: "PARSE_PO_PDF",
  VIEW_SHIPMENTS: "VIEW_SHIPMENTS",
  CREATE_SHIPMENT: "CREATE_SHIPMENT",
  UPDATE_SHIPMENT: "UPDATE_SHIPMENT",
  COUPLE_DECOUPLE_PO: "COUPLE_DECOUPLE_PO",
  VIEW_EXPORT_BULKING: "VIEW_EXPORT_BULKING",
  CREATE_EXPORT_BULKING: "CREATE_EXPORT_BULKING",
  UPDATE_EXPORT_BULKING: "UPDATE_EXPORT_BULKING",
  UPDATE_EXPORT_OPERATIONS: "UPDATE_EXPORT_OPERATIONS",
  UPDATE_EXPORT_DOCUMENTATION: "UPDATE_EXPORT_DOCUMENTATION",
  UPDATE_EXPORT_BULKING_STATUS: "UPDATE_EXPORT_BULKING_STATUS",
  MANAGE_SHIPPERS: "MANAGE_SHIPPERS",
  MANAGE_IMPORT_MASTERS: "MANAGE_IMPORT_MASTERS",
  MANAGE_EXPORT_MASTERS: "MANAGE_EXPORT_MASTERS",
  MANAGE_AGENTS: "MANAGE_AGENTS",
  MANAGE_SURVEYORS: "MANAGE_SURVEYORS",
  MANAGE_COMMODITIES: "MANAGE_COMMODITIES",
  VIEW_PO_PDF_AI_USAGE: "VIEW_PO_PDF_AI_USAGE",
  VIEW_EXPORT_DOCUMENTATION: "VIEW_EXPORT_DOCUMENTATION",
  ASSIGN_EXPORT_BULKING_DOCUMENTATION: "ASSIGN_EXPORT_BULKING_DOCUMENTATION",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** All known permission keys (for validation and UI). */
export const ALL_PERMISSION_KEYS: readonly string[] = Object.values(PERMISSIONS);

const ALL_PERM_SET = new Set<string>(ALL_PERMISSION_KEYS);

const IMPORT_OFFICER_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.VIEW_TRANSACTIONS,
  PERMISSIONS.CREATE_TRANSACTION,
  PERMISSIONS.UPDATE_TRANSACTION,
  PERMISSIONS.UPDATE_STATUS,
  PERMISSIONS.UPLOAD_DOCUMENT,
  PERMISSIONS.VIEW_PO_INTAKE,
  PERMISSIONS.UPDATE_PO_INTAKE,
  PERMISSIONS.TAKE_OWNERSHIP,
  PERMISSIONS.CREATE_PO_INTAKE_TEST,
  PERMISSIONS.IMPORT_PO_CSV,
  PERMISSIONS.PARSE_PO_PDF,
  PERMISSIONS.VIEW_SHIPMENTS,
  PERMISSIONS.CREATE_SHIPMENT,
  PERMISSIONS.UPDATE_SHIPMENT,
  PERMISSIONS.COUPLE_DECOUPLE_PO,
  PERMISSIONS.VIEW_EXPORT_BULKING,
  PERMISSIONS.CREATE_EXPORT_BULKING,
  PERMISSIONS.UPDATE_EXPORT_BULKING,
  PERMISSIONS.UPDATE_EXPORT_BULKING_STATUS,
];

const ADMIN_IMPORT_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.MANAGE_USERS,
  PERMISSIONS.VIEW_PO_INTAKE,
  PERMISSIONS.CREATE_PO_INTAKE_TEST,
  PERMISSIONS.UPDATE_PO_INTAKE,
  PERMISSIONS.TAKE_OWNERSHIP,
  PERMISSIONS.IMPORT_PO_CSV,
  PERMISSIONS.PARSE_PO_PDF,
  PERMISSIONS.VIEW_SHIPMENTS,
  PERMISSIONS.CREATE_SHIPMENT,
  PERMISSIONS.UPDATE_SHIPMENT,
  PERMISSIONS.UPDATE_STATUS,
  PERMISSIONS.COUPLE_DECOUPLE_PO,
  PERMISSIONS.MANAGE_IMPORT_MASTERS,
  PERMISSIONS.MANAGE_SHIPPERS,
  PERMISSIONS.VIEW_PO_PDF_AI_USAGE,
];

const ADMIN_EXPORT_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.MANAGE_USERS,
  PERMISSIONS.VIEW_EXPORT_BULKING,
  PERMISSIONS.VIEW_EXPORT_DOCUMENTATION,
  PERMISSIONS.CREATE_EXPORT_BULKING,
  PERMISSIONS.UPDATE_EXPORT_BULKING,
  PERMISSIONS.UPDATE_EXPORT_OPERATIONS,
  PERMISSIONS.UPDATE_EXPORT_DOCUMENTATION,
  PERMISSIONS.UPDATE_EXPORT_BULKING_STATUS,
  PERMISSIONS.ASSIGN_EXPORT_BULKING_DOCUMENTATION,
  PERMISSIONS.MANAGE_EXPORT_MASTERS,
  PERMISSIONS.UPLOAD_DOCUMENT,
];

const EXPORT_BULKING_DOCUMENT_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.VIEW_EXPORT_BULKING,
  PERMISSIONS.VIEW_EXPORT_DOCUMENTATION,
  PERMISSIONS.UPDATE_EXPORT_DOCUMENTATION,
  PERMISSIONS.UPLOAD_DOCUMENT,
];

const ROLE_PERMISSIONS: Record<string, readonly Permission[]> = {
  [ROLES.ADMIN]: [...ALL_PERMISSION_KEYS] as Permission[],
  [ROLES.ADMIN_IMPORT]: ADMIN_IMPORT_PERMISSIONS,
  [ROLES.ADMIN_EXPORT]: ADMIN_EXPORT_PERMISSIONS,
  [ROLES.IMPORT_OFFICER]: IMPORT_OFFICER_PERMISSIONS,
  [ROLES.EXIM_OFFICER]: IMPORT_OFFICER_PERMISSIONS,
  [ROLES.VIEWER]: [
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.VIEW_PO_INTAKE,
    PERMISSIONS.CREATE_PO_INTAKE_TEST, /* temporary for E2E testing until SaaS integration */
    PERMISSIONS.IMPORT_PO_CSV,
    PERMISSIONS.PARSE_PO_PDF,
    PERMISSIONS.VIEW_SHIPMENTS,
  ],
  [ROLES.DOCS]: [
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.VIEW_PO_INTAKE,
    PERMISSIONS.VIEW_SHIPMENTS,
  ],
  [ROLES.EXPORT_BULKING_OPERATION]: [
    PERMISSIONS.VIEW_EXPORT_BULKING,
    PERMISSIONS.VIEW_EXPORT_DOCUMENTATION,
    PERMISSIONS.CREATE_EXPORT_BULKING,
    PERMISSIONS.UPDATE_EXPORT_OPERATIONS,
    PERMISSIONS.UPDATE_EXPORT_BULKING_STATUS,
  ],
  [ROLES.EXPORT_BULKING_DOCUMENT]: EXPORT_BULKING_DOCUMENT_PERMISSIONS,
  [ROLES.EXPORT_BULKING_DOCUMENTATION]: EXPORT_BULKING_DOCUMENT_PERMISSIONS,
  [ROLES.EXPORT_BULKING_LEAD_DOCUMENTATION]: [
    PERMISSIONS.VIEW_EXPORT_BULKING,
    PERMISSIONS.VIEW_EXPORT_DOCUMENTATION,
    PERMISSIONS.UPDATE_EXPORT_DOCUMENTATION,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.ASSIGN_EXPORT_BULKING_DOCUMENTATION,
  ],
};

/** Normalized role key (uppercase) for lookup. */
function normalizeRole(role: string): string {
  return role.toUpperCase();
}

/** Normalize override list to known permissions only. */
export function normalizePermissionOverrides(overrides: unknown): string[] {
  if (!Array.isArray(overrides)) return [];
  const out: string[] = [];
  for (const p of overrides) {
    if (typeof p === "string" && ALL_PERM_SET.has(p)) out.push(p);
  }
  return out;
}

/** Union of role permissions and optional per-user overrides. */
export function computeEffectivePermissions(role: string, overrides: string[]): ReadonlySet<string> {
  const base = getPermissionsForRole(role);
  const out = new Set<string>(base);
  for (const p of normalizePermissionOverrides(overrides)) out.add(p);
  return out;
}

/** Whether the user (role + optional overrides) has the permission. */
export function userHasPermission(
  role: string,
  overrides: string[] | null | undefined,
  permission: string
): boolean {
  return computeEffectivePermissions(role, overrides ?? []).has(permission);
}

/** Role-only check (no overrides). */
export function hasPermission(role: string, permission: string): boolean {
  return userHasPermission(role, [], permission);
}

/** Returns all permissions for a role (for future use). */
export function getPermissionsForRole(role: string): ReadonlySet<string> {
  const key = normalizeRole(role);
  const list = ROLE_PERMISSIONS[key] ?? [];
  return new Set(list);
}

/** Valid role values for DB/validation. */
export const VALID_ROLES: readonly string[] = Object.values(ROLES);

/** Read shipper master catalog (operational + admin). */
export const PERMS_READ_SHIPPER_MASTER = [
  PERMISSIONS.VIEW_EXPORT_BULKING,
  PERMISSIONS.VIEW_PO_INTAKE,
  PERMISSIONS.VIEW_SHIPMENTS,
  PERMISSIONS.VIEW_TRANSACTIONS,
  PERMISSIONS.MANAGE_IMPORT_MASTERS,
  PERMISSIONS.MANAGE_EXPORT_MASTERS,
  PERMISSIONS.MANAGE_SHIPPERS,
] as const;

/** Import-side master data (shipper entity, PT, plants). */
export const PERMS_MANAGE_IMPORT_MASTERS = [
  PERMISSIONS.MANAGE_IMPORT_MASTERS,
  PERMISSIONS.MANAGE_SHIPPERS,
] as const;

/** Export-side master data (agents, surveyors, commodities, load ports). */
export const PERMS_MANAGE_EXPORT_MASTERS = [
  PERMISSIONS.MANAGE_EXPORT_MASTERS,
  PERMISSIONS.MANAGE_SHIPPERS,
  PERMISSIONS.MANAGE_AGENTS,
  PERMISSIONS.MANAGE_SURVEYORS,
  PERMISSIONS.MANAGE_COMMODITIES,
] as const;
